const products = [
  {
    img: "images/home/image1.png",
    like: "images/like.png",
    discount: "-50%",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    fullstar: 2,
    star: 3,
  },
  {
    img: "images/home/image2.png",
    like: "images/like.png",
    discount: "-50%",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    fullstar: 3,
    star: 2,
  },
  {
    img: "images/home/image3.png",
    like: "images/like.png",
    discount: "-50%",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    fullstar: 5,
    star: 0,
  },

  {
    img: "images/home/image4.png",
    like: "images/like.png",
    discount: "-50%",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    fullstar: 4,
    star: 1,
  },
];

const news = [
  {
    img: "images/home/image5.png",
    like: "images/like.png",
    price: "599,99 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
  {
    img: "images/home/image3.png",
    like: "images/like.png",
    price: "44,50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    fullstar: 5,
    star: 0,
  },
  {
    img: "images/home/image4.png",
    like: "images/like.png",
    price: "159,99 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
  {
    img: "images/home/image6.png",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
];

const popular = [
  {
    img: "images/home/image6.png",
    like: "images/like.png",
    price: "77,99 ₽",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
  {
    img: "images/home/image4.png",
    like: "images/like.png",
    price: "159,50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    fullstar: 5,
    star: 0,
  },
  {
    img: "images/home/image5.png",
    like: "images/like.png",
    price: "599,99 ₽",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
  {
    img: "images/home/image2.png",
    like: "images/like.png",
    price: "49,39 ₽",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    fullstar: 2,
    star: 3,
  },
];

const special = [
  {
    img: "images/home/img1.png",
    name: "Оформите карту «Северяночка»",
    desc: "И получайте бонусы при покупке в магазинах и на сайте",
  },
  {
    img: "images/home/img2.png",
    name: "Покупайте акционные товары",
    desc: "И получайте вдвое больше бонусов",
  },
];

const statyi = [
  {
    img: "images/home/s1.png",
    date: "05.03.2021",
    name: "Режим использования масок и перчаток на территории магазинов",
    desc: "Подробная информация о режимах использования масок и перчаток на территории магазинов 'ЛЕНТА'. Информация обновляется каждый будний день.",
  },
  {
    img: "images/home/s2.png",
    date: "05.03.2021",
    name: "Весеннее настроение для каждой",
    desc: "8 Марта – это не просто Международный женский день, это ещё день тюльпанов, приятных сюрпризов и праздничных тёплых пожеланий.",
  },
  {
    img: "images/home/s3.png",
    date: "05.03.2021",
    name: "ЗОЖ или ФАСТФУД. А вы на чьей стороне? Голосуем!",
    desc: "Голосуйте за любимые категории, выбирайте категорию-победителя в мобильном приложении и получайте кешбэк 10% баллами в апреле!",
  },
];

const maps = [
  {
    name: "п.Щельяюр",
    iframe: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d47970.919553574415!2d69.17803588897986!3d41.283133012349914!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8ba578f4f58d%3A0xd7a2ecf23413b7a0!2sNajot%20Ta&#39;lim%20Chilonzor%20Filial!5e0!3m2!1sen!2s!4v1680521150731!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
  },
  {
    name: "д.Вертеп",
    iframe: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d47970.919553574415!2d69.17803588897986!3d41.283133012349914!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8bfaedfe3e1d%3A0x23ac4a5a705b84ab!2zTmFqb3QgVGHigJlsaW0!5e0!3m2!1sen!2s!4v1680521184044!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
  },
  {
    name: "с.Краснобор",
    iframe:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3038.9420246067557!2d71.78338012946428!3d40.387977513378424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bb83a471c6b55b%3A0x9927f2609db0d333!2sNajot%20Ta&#39;lim%20Farg&#39;ona!5e0!3m2!1sen!2s!4v1680521214353!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  },
  {
    name: "д.Диюр",
    iframe:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3038.9420246067557!2d71.78338012946428!3d40.387977513378424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bb83a471c6b55b%3A0x9927f2609db0d333!2sNajot%20Ta&#39;lim%20Farg&#39;ona!5e0!3m2!1sen!2s!4v1680521214353!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  },
];

const searchproducts = [
  {
    id: 1,
    img: "images/home/image1.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
  },
  {
    id: 2,
    img: "images/home/image2.png",
    stars: "images/home/5stars.svg",
    like: "images/like.png",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
  },
  {
    id: 3,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
  },

  {
    id: 4,
    img: "images/home/image4.png",
    like: "images/like.png",
    stars: "images/home/2stars.svg",
    price: "44.50 ₽",
    default_price: "50.50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
  },
  {
    id: 5,
    img: "images/home/image5.png",
    stars: "images/home/5stars.svg",
    like: "images/like.png",
    price: "599,99 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 6,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "44,50 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
  },
  {
    id: 7,
    img: "images/home/image4.png",
    stars: "images/home/5stars.svg",
    like: "images/like.png",
    price: "159,99 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 8,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 9,
    img: "images/home/image1.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 10,
    img: "images/home/image4.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 11,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 12,
    img: "images/home/image4.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 13,
    img: "images/home/image5.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 14,
    img: "images/home/image2.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 15,
    img: "images/home/image1.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 16,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 17,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 18,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 19,
    img: "images/home/image5.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 20,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 21,
    img: "images/home/image2.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 22,
    img: "images/home/image4.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 23,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 24,
    img: "images/home/image5.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 25,
    img: "images/home/image2.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 26,
    img: "images/home/image4.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 27,
    img: "images/home/image4.png",
    stars: "images/home/5stars.svg",
    like: "images/like.png",
    price: "159,99 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 28,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 29,
    img: "images/home/image1.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 30,
    img: "images/home/image4.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 31,
    img: "images/home/image3.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 32,
    img: "images/home/image6.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
  {
    id: 33,
    img: "images/home/image1.png",
    stars: "images/home/2stars.svg",
    like: "images/like.png",
    price: "49,39 ₽",
    payment: "С картой",
    default_payment: "Обычная",
    desc: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
  },
];
